/* Auto-generated by ticker-admin.html — manuel düzenleme önerilmez */
window.SHIMANO_TICKER = [
  {
    title: "Shimano launched new Saint PD-G8040 and Deore XT PD-M8240 flat pedals designed for gravity and trail riding.",
    added: "2026-04-20"
  }
];
