/* AUTO-GENERATED by tools/gen_ticker_auto.py — do not edit by hand.
   Replaced on every stock update push. */
window.SHIMANO_TICKER_AUTO = [
  {
    "title": "Stock updated: 06 Oct 2026",
    "added": "2026-10-06",
    "expires": "2026-10-13",
    "auto": "stamp"
  }
];
